language: node_js
node_js:
  - "0.8"

install:
  - "bash scripts/install_xtuple.sh -ipn"

before_script:
  - "cd node-datasource"
  - "node main.js &"
  - "sleep 10"
  - "cd .."

script:
  - "npm run-script test-datasource"
  - "npm run-script test"

  # test an upgrade from 4.4.0
  - "wget http://sourceforge.net/projects/postbooks/files/03%20PostBooks-databases/4.4.0/postbooks_demo-4.4.0.backup"
  - "./scripts/build_app.js -d upgrade_test -i -b ./postbooks_demo-4.4.0.backup"
